config/routes.rb
Rails.application.routes.draw do
  resources :experiments
  root to: 'experiments#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
end

app/models/user.rb
class User < OpenStruct
  def self.from_omniauth(auth)
    self.new({
      id:         auth["uid"],
      name:       auth["info"]["name"],
      email:      auth["info"]["email"],
      account_id: auth["extra"]["raw_info"]["account_id"]
    })
  end

  def as_json(*args)
    table
  end

  def tradegecko_admin?
    account_id == 4
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def authenticate_user!
    redirect_to "/auth/tradegecko" unless user_signed_in?
  end

  def user_signed_in?
    session[:user]
  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_experiment, only: [:show, :edit, :update, :destroy]

  def index
    @experiments = Experiment.all
  end

  def show
  end

  def new
    @experiment = Experiment.new
  end

  def edit
  end

  def create
    @experiment = Experiment.new(experiment_params)

    if @experiment.save
      redirect_to @experiment, notice: 'Experiment was successfully created.'
    else
      render :new
    end
  end

  def update
    if @experiment.update(experiment_params)
      redirect_to @experiment, notice: 'Experiment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @experiment.destroy
    redirect_to experiments_url, notice: 'Experiment was successfully destroyed.'
  end

private

  def set_experiment
    @experiment = Experiment.find(params[:id])
  end

  def experiment_params
    params.require(:experiment).permit(:key, :instrument_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    user = User.from_omniauth(auth_hash)
    if user.tradegecko_admin?
      session[:user] = user.as_json
      redirect_to root_url
    else
      redirect_to "https://www.tradegecko.com"
    end
  end

  def destroy
    session[:user] = nil
    redirect_to root_url, notice: "Signed out!"
  end

  def auth_hash
    env["omniauth.auth"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
      { success: 'alert-success', error: 'alert-danger', warning: 'alert-warning'}[flash_type.to_sym]
   end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "text-center alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'})
        concat message
      end)
      flash.clear
    end
    nil
  end
end

app/views/experiments/_form.html.erb
<%= form_for @experiment, :html => { :class => "form-horizontal experiment" } do |f| %>

    <% if @experiment.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@experiment.errors.count, "error") %> prohibited this experiment from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @experiment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :key, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :key, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :instrument_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :instrument_id, :class => 'form-control' %>
    </div>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            experiments_path, :class => 'btn btn-default' %>

<% end %>

app/views/experiments/edit.html.erb
<%- model_class = Experiment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/experiments/index.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th colspan="5">
        Science Experiments
      </th>
    </tr>
  </thead>
  <tbody>
    <% @experiments.each do |experiment| %>
      <tr>
        <td><%= link_to experiment.key, experiment_path(experiment) %></td>
        <td><%= experiment.instrument_id %></td>
        <td><%= experiment.created_at %></td>
      </tr>
    <% end %>

    <% Redis.tradegecko.keys("science.*").each do |experiment| %>
      <tr>
        <td><%= experiment %></td>
        <td><%= Redis.tradegecko.llen(experiment) %> Mismatches</td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_experiment_path,
            :class => 'btn btn-primary' %>

app/views/experiments/new.html.erb
<%- model_class = Experiment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/experiments/show.html.erb
<%- model_class = Experiment -%>
<div class="page-header">
  <h1><%= @experiment.key %></h1>
</div>

<script type="text/javascript"
    src="https://sdk.librato.com/librato-sdk-v0.5.1-min.js"
    data-librato_email="<%= ENV['LIBRATO_EMAIL'] %>"
    data-librato_token="<%= ENV['LIBRATO_TOKEN'] %>">
</script>

<div class="librato-metrics" data-instrument_id="<%= @experiment.instrument_id %>"></div>

<h4>Errors</h4>
<%= Redis.tradegecko.llen("science.#{@experiment.key}.mismatch") %> Mismatches

<% Redis.tradegecko.lrange("science.#{@experiment.key}.mismatch", 0, 50).each do |value| %>
  <%= value %>
<% end %>

<%= link_to t('.back', :default => t("helpers.links.back")),
              experiments_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_experiment_path(@experiment), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              experiment_path(@experiment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TradeGecko Developer Tools" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand" href="/">TradeGecko</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Experiments", experiments_path %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Logout", "/logout"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <ol class="breadcrumb">
          <li><a href="/">Developer Tools</a></li>
          <li>Experiments</li>
        </ol>
      </div>
      <div class="row">
        <div class="col-lg-9">
          <%= flash_messages %>
          <%= yield %>
        </div>
      </div><!--/row-->


    </div> <!-- /container -->

    <footer class="footer">
      <p>&copy; TradeGecko Pte Ltd 2015</p>
    </footer>
  </body>
</html>